// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xewviiqtckgjnhteuipp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhld3ZpaXF0Y2tnam5odGV1aXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzg3NDEsImV4cCI6MjA2MzMxNDc0MX0.cst1INDxTGRfYw1AhtaP_hZ80UNiB9sl4byHJvl-3T4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);